### ISSUE TITLE
Rosjack_read showing error [please check]

### ISSUE THREAD

**Issue by hs2041** [balkce/beamform#2]
Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error

**Comment by balkce** [comment]
It seems that the jackaudio server may not be running with RealTime priorities. Either you need to add your user to the "audio" group, or check the RT scheduling in your operating system.

More information: https://jackaudio.org/faq/linux_rt_config.html

**Comment by hs2041** [comment]
Thanks for the quick reply!!
Just solved it. I used this resource: [https://askubuntu.com/questions/166126/unable-to-start-jack-cannot-allocate-memory]

**Comment by balkce** [comment]
I'm glad you got it working. Closing issue.
